picom(1)
========
:doctype:     manpage
:man source:  picom
:man version: {picom-version}
:man manual:  User Commands

NAME
----
picom - a compositor for X11

SYNOPSIS
--------
*picom* ['OPTIONS']

DESCRIPTION
-----------
picom is a compositor based on Dana Jansens' version of xcompmgr (which itself was written by Keith Packard). It includes some improvements over the original xcompmgr.

OPTIONS
-------
*-h*, *--help*::
	Get the usage text embedded in program code, which may be more up-to-date than this man page.

*-b*, *--daemon*::
	Daemonize process. Fork to background after initialization. This option can only be set from the command line, setting this in the configuration file will have no effect.

*--log-level*::
	Set the log level. Possible values are "TRACE", "DEBUG", "INFO", "WARN", "ERROR", in increasing level of importance. Case doesn't matter. If using the "TRACE" log level, it's better to log into a file using *--log-file*, since it can generate a huge stream of logs.

*--log-file*::
	Set the log file. If *--log-file* is never specified, logs will be written to stderr. Otherwise, logs will to written to the given file, though some of the early logs might still be written to the stderr.

*--show-all-xerrors*::
	Show all X errors (for debugging).

*--backend* 'BACKEND'::
	Specify the backend to use. `glx` is the default one.
+
--
* `glx` (OpenGL) backend performs all rendering operations with OpenGL. It is more friendly to some VSync methods. It requires proper OpenGL 2.0 support from your driver and hardware. You may wish to look at the GLX performance optimization options below. *--xrender-sync-fence* might be needed on some systems to avoid delay in changes of screen contents.
--

*--glx-no-stencil*::
  GLX backend: Avoid using stencil buffer, useful if you don't have a stencil buffer. Might cause incorrect opacity when rendering transparent content (but never practically happened). My tests show a 15% performance boost. Recommended.

*--glx-no-rebind-pixmap*::
	GLX backend: Avoid rebinding pixmap on window damage. Probably could improve performance on rapid window content changes, but is known to break things on some drivers (LLVMpipe, xf86-video-intel, etc.). Recommended if it works.

*--xrender-sync-fence*::
	Use X Sync fence to sync clients' draw calls, to make sure all draw calls are finished before picom starts drawing. Needed on nvidia-drivers with GLX backend for some users.

SIGNALS
-------

* picom reinitializes itself upon receiving `SIGUSR1`.

BUGS
----
Please submit bug reports to <https://github.com/yshui/picom>.

Out dated information in this man page is considered a bug.

RESOURCES
---------
Homepage: <https://github.com/yshui/picom>

SEE ALSO
--------
*xcompmgr*(1)
